Reset the scheduler so that slack variables used to explain infeasibility do not corrupt future attempts to schedule. Also, always check if the user wants to try finding the minimum feasible clock period that would satisfy the scheduler while still propagating the scheduler's error
New example, more helpful error message:
```
Error: INVALID_ARGUMENT: cannot achieve the specified clock period. Try `--clock_period_ps=721`. The reason the scheduler gave is: INVALID_ARGUMENT: __alu__AluProc_0_next: cannot satisfy the given I/O constraints. Would succeed with: {alu__p3_data_ins→alu__p5_outs with maximum latency ≥ 3}, {alu__p3_ins→alu__p5_outs with maximum latency ≥ 3}
```
PiperOrigin-RevId: 847823548