Instead of absl, use standard headers for std::{string_view,variant,optional}.
Exception: We do use absl::visit, so need the absl header when used.
PiperOrigin-RevId: 543907752